### PR TITLE
footer WIP

### PR DESCRIPTION
**Pull request by wdwatkins**
CSS isn't quite working right, width isn't being limited and might want to change background.  I assume there needs to be a `width=760px` somewhere, or a section isn't referencing something it should.

Also need to decide what related content we want.

### CODE REVIEW

**Comment by jordansread** [comment]
@wdwatkins can you throw a screenshot in the comments so we can easily see what this looks like?

**Comment by wdwatkins** [comment]
image

**Comment by wdwatkins** [comment]
Related blogs can be turned off if we just want to show vizzes

**Comment by jordansread** [comment]
where's our css wizard when ya need it? :+1:

**Comment by wdwatkins** [comment]
vizlab icon path is in the footer template in the vizlab package, I had to change it

**Comment by jordansread** [comment]
so that package has an update?

**Comment by jordansread** [comment]
is that related to

```
> do.call(cmd.args$fun, if(is.null(cmd.args$funargs)) list() else cmd.args$funargs)
Read 9560 items
Error in UseMethod("publish") : 
  no applicable method for 'publish' applied to an object of class "c('footer', 'publisher', 'viz')"
Calls: do.call ... publish.page -> lapply -> FUN -> publish.character -> publish
In addition: There were 13 warnings (use warnings() to see them)
Execution halted
```

?

**Comment by jordansread** [comment]
@wdwatkins what did you do to get this to work? I am not able to build it

**Comment by wdwatkins** [comment]
@jread-usgs ah sorry, footer functionality is in my outstanding vizlab PR.  @jiwalker-usgs should we go ahead and merge that?  Should be functional, but it just doesn't have a test yet.  I will try to get that going this morning.  The test viz was still having issues last week.

**Pull request merged**
